-- 034_settings_bank_terms.sql
-- Add bank details and invoice terms & conditions to store settings for wholesale invoice printing

ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS bank_name TEXT DEFAULT 'TAMILNAD MERCANTILE BANK LTD',
  ADD COLUMN IF NOT EXISTS bank_account_no TEXT DEFAULT '391700050900006',
  ADD COLUMN IF NOT EXISTS bank_ifsc TEXT DEFAULT 'TMBL0000391',
  ADD COLUMN IF NOT EXISTS bank_branch TEXT,
  ADD COLUMN IF NOT EXISTS invoice_terms TEXT DEFAULT '1. GOODS ONCE SOLD WILL NOT BE ACCEPTED.
2. CHEQUE RETURN CHARGES RS.500 WILL BE TAKEN EXTRA.
3. ALL DISPUTES SUBJECT TO LOCAL JURISDICTION.';
